### ISSUE TITLE
Ta høyde for helsyntetiske fnr/dnr

### ISSUE THREAD

**Issue by charliemidtlyng** [navikt/fnrvalidator#116]
Dolly ønsker å gå bort fra å bruke vanlige fødselsnummer og D-nummer og gå over til helsyntetiske varianter. 
Basert på #dolly på Slack vil NAVs syntetiske varianter være +40 på måned og Skatts variant er +80 på måned. 

Eksempel på verdier:

Eksempler på NAV helsyntetiske identer (fra Identpool)
Fødselsdato Kjønn  Fødselsnummer D-nummer
15.10.1976  Mann   15507600333   55507608360
29.02.2020  Kvinne 29422059278   69422056629
05.04.2003  Kvinne 05440355678   45440356293
12.02.1994  Mann   12429400544   52429405181
12.10.1952  Mann   12505209719   52505209540
21.08.1936  Kvinne 21483609245   61483601467
21.12.1897  Kvinne 21528704651   61528703428 

Eksempler på Tenor helsyntetiske identer mottatt fra Skatt
Fødselsdato Kjønn  Fødselsnummer D-nummer
17.11.2020  Mann   17912099997   57912075186
29.02.2020  Kvinne 29822099635   69822075096
05.04.2003  Kvinne 05840399895   45840375084
12.02.1994  Mann   12829499914   52829400197
12.10.1952  Mann   12905299938   52905200100
21.08.1936  Kvinne 21883649874   61883600222
21.12.1897  Kvinne 21929774873   61929750062 

Fnrvalidator bør kanskje ta høyde for disse verdiene slik at det kan tas i bruk av alle som har avhengighet til denne?

**Comment by jksolbakken** [comment]
Se kommentar i #117
