### ISSUE TITLE
Feil i Typescript typene til OkResult.Type

### ISSUE THREAD

**Issue by KennethHoff** [navikt/fnrvalidator#435]
Det står at `dnr`, `fnr`, og `hnr` er de mulige typene, men jeg fikk `tnr` som resultat

![image](https://github.com/navikt/fnrvalidator/assets/17124533/e54b4292-21e1-4927-b099-1cbc1489377c)

**Comment by Oddsor** [comment]
Dette skal ikke være et problem i nyere versjoner av bilioteket (tnr er inkludert i typedefinisjonen som genereres under bygg).
Lukker denne saken.
