### ISSUE TITLE
invalid date på syntetisk d-nummer

### ISSUE THREAD

**Issue by vebnor** [navikt/fnrvalidator#469]
![image](https://github.com/navikt/fnrvalidator/assets/25080417/09553034-3bea-4910-b0f9-f3956cfb59e9)
![image](https://github.com/navikt/fnrvalidator/assets/25080417/b4f974cd-c450-4df0-b5a1-6aee442e53a1)

Funksjonen som kjøres er idnr("46879700922"). Men får error om at det er invalid date. Identen er importert fra Test-Norge og ligger i Dolly. 
Er det støtte for syntetiske d-nummer? Ser i hvert fall ut som det ble lagt til [her](https://github.com/navikt/fnrvalidator/commit/291b887ab1240ced9515b88724c824300c5b36bf)

**Comment by khopland** [comment]
ser ut som syntetisk folkeregister lager idnr med +80 på måned [ref](https://skatteetaten.github.io/folkeregisteret-api-dokumentasjon/ny-versjon-av-syntetisk-folkeregister/)

**Comment by poroshinaleksei** [comment]
Er det planlagt at oppdatering kommer? @jksolbakken
