### ISSUE TITLE
Publisering på npm?

### ISSUE THREAD

**Issue by aulonm** [navikt/fnrvalidator#500]
Hei!

Først må jeg si veldig deilig at dere har en pakke som dette. Har vært helt nydelig å kunne bruke hos oss i OBOS. 

Jeg ser at pakken er på v2 med ts support som er helt konge, men ingen planer om å publisere på npm? 

Ikke at det er et veldig stort problem sånn egentlig, kan bare hente fra github packages i stedet 🙌 

Tenkte bare høre på begrunnelsen, kan lukkes hvis planen er å bare publisere på github.

Takk igjen, bra pakka ikke forble EOL ❤️

**Comment by Magnuti** [comment]
Pakken ligger på npm https://www.npmjs.com/package/@navikt/fnrvalidator

**Comment by aulonm** [comment]
Versjon 1.3.0 ja, men ikke versjon 2.1.0 som dere har her :)

**Comment by Magnuti** [comment]
Så først nå at issuet ditt var at npm pakken fremdeles er på versjon 1.3.0. Støttes at det bør fikses! Særlig når det står at 2.1.0 finnes på npm

![image](https://github.com/user-attachments/assets/20815a8b-0ed6-4244-83bf-41e4a0c71078)

**Comment by oivindjenssen** [comment]
Noe nytt om dette? Blir siste versjon publisert via npm?

**Comment by espen** [comment]
Nice @vebnor. Er det noen breaking changes i v2? Finner ingen info på https://github.com/navikt/fnrvalidator/releases
